//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizca.Bff.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bizca.Bff.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bundle is invalid..
        /// </summary>
        internal static string BUNDLE_INVALID {
            get {
                return ResourceManager.GetString("BUNDLE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à channel type is invalid..
        /// </summary>
        internal static string CHANNEL_TYPE_INVALID {
            get {
                return ResourceManager.GetString("CHANNEL_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à civility is invalid..
        /// </summary>
        internal static string CIVILITY_INVALID {
            get {
                return ResourceManager.GetString("CIVILITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à civility is required..
        /// </summary>
        internal static string CIVILITY_REQUIRED {
            get {
                return ResourceManager.GetString("CIVILITY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à code insee is required..
        /// </summary>
        internal static string CODE_INSEE_REQUIRED {
            get {
                return ResourceManager.GetString("CODE_INSEE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à confirmation code is required..
        /// </summary>
        internal static string CONFIRMATION_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("CONFIRMATION_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à economicActivity is invalid..
        /// </summary>
        internal static string ECONOMIC_ACTIVITY_INVALID {
            get {
                return ResourceManager.GetString("ECONOMIC_ACTIVITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à economicActivity is required..
        /// </summary>
        internal static string ECONOMIC_ACTIVITY_REQUIRED {
            get {
                return ResourceManager.GetString("ECONOMIC_ACTIVITY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue chez Bizca! Confirmons ton adresse email..
        /// </summary>
        internal static string EMAIL_CONFIRMATION_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_CONFIRMATION_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à email is invalid..
        /// </summary>
        internal static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ^\w+([-+.&apos;]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$.
        /// </summary>
        internal static string EMAIL_REGEX {
            get {
                return ResourceManager.GetString("EMAIL_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à external user Identifier maximun length exceed..
        /// </summary>
        internal static string EXTERNAL_USERID_MAXIMUM_LENGTH_EXCEED {
            get {
                return ResourceManager.GetString("EXTERNAL_USERID_MAXIMUM_LENGTH_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à externalUserId is required..
        /// </summary>
        internal static string EXTERNAL_USERID_REQUIRED {
            get {
                return ResourceManager.GetString("EXTERNAL_USERID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à firstname maximun length exceed..
        /// </summary>
        internal static string FIRSTNAME_MAXIMUN_LENGTH_EXCEED {
            get {
                return ResourceManager.GetString("FIRSTNAME_MAXIMUN_LENGTH_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à firstName is required..
        /// </summary>
        internal static string FIRSTNAME_REQUIRED {
            get {
                return ResourceManager.GetString("FIRSTNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à lastname maximun length exceed..
        /// </summary>
        internal static string LASTNAME_MAXIMUN_LENGTH_EXCEED {
            get {
                return ResourceManager.GetString("LASTNAME_MAXIMUN_LENGTH_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à lastName is required..
        /// </summary>
        internal static string LASTNAME_REQUIRED {
            get {
                return ResourceManager.GetString("LASTNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à partnerCode is required..
        /// </summary>
        internal static string PARTNER_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("PARTNER_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à password is required..
        /// </summary>
        internal static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à phoneNumber is required..
        /// </summary>
        internal static string PHONENUMBER_REQUIRED {
            get {
                return ResourceManager.GetString("PHONENUMBER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à procedure type is invalid..
        /// </summary>
        internal static string PROCEDURE_TYPE_INVALID {
            get {
                return ResourceManager.GetString("PROCEDURE_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à procedure type is required..
        /// </summary>
        internal static string PROCEDURE_TYPE_REQUIRED {
            get {
                return ResourceManager.GetString("PROCEDURE_TYPE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à resource login is required..
        /// </summary>
        internal static string RESOURCE_LOGIN_REQUIRED {
            get {
                return ResourceManager.GetString("RESOURCE_LOGIN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à subscription code is required..
        /// </summary>
        internal static string SUBSCRIPTION_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_CODE_REQUIRED", resourceCulture);
            }
        }
    }
}
