//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizca.User.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bizca.User.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à street is invalid..
        /// </summary>
        public static string ADDRESS_STREET_INVALID {
            get {
                return ResourceManager.GetString("ADDRESS_STREET_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à zipCode is invalid..
        /// </summary>
        public static string ADDRESS_ZIPCODE_INVALID {
            get {
                return ResourceManager.GetString("ADDRESS_ZIPCODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à addressName is invalid..
        /// </summary>
        public static string ADDRESSNAME_INVALID {
            get {
                return ResourceManager.GetString("ADDRESSNAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à birthCity is invalid..
        /// </summary>
        public static string BIRTHCITY_INVALID {
            get {
                return ResourceManager.GetString("BIRTHCITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à birthCountry is invalid..
        /// </summary>
        public static string BIRTHCOUNTRY_INVALID {
            get {
                return ResourceManager.GetString("BIRTHCOUNTRY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à birthDate is invalid..
        /// </summary>
        public static string BIRTHDATE_INVALID {
            get {
                return ResourceManager.GetString("BIRTHDATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à channel resource is required..
        /// </summary>
        public static string CHANNEL_RESOURCE_REQUIRED {
            get {
                return ResourceManager.GetString("CHANNEL_RESOURCE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à channelType is invalid..
        /// </summary>
        public static string CHANNEL_TYPE_INVALID {
            get {
                return ResourceManager.GetString("CHANNEL_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à city is invalid..
        /// </summary>
        public static string CITY_INVALID {
            get {
                return ResourceManager.GetString("CITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à city is required..
        /// </summary>
        public static string CITY_REQUIRED {
            get {
                return ResourceManager.GetString("CITY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à civility is invalid..
        /// </summary>
        public static string CIVILITY_INVALID {
            get {
                return ResourceManager.GetString("CIVILITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à civility is required..
        /// </summary>
        public static string CIVILITY_REQUIRED {
            get {
                return ResourceManager.GetString("CIVILITY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à confirmationCode is required..
        /// </summary>
        public static string CONFIRMATION_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("CONFIRMATION_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à country is invalid..
        /// </summary>
        public static string COUNTRY_CODE_INVALID {
            get {
                return ResourceManager.GetString("COUNTRY_CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ^[A-Za-z]{2}$.
        /// </summary>
        public static string COUNTRY_CODE_REGEX {
            get {
                return ResourceManager.GetString("COUNTRY_CODE_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à country is required..
        /// </summary>
        public static string COUNTRY_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("COUNTRY_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à economicActivity is invalid..
        /// </summary>
        public static string ECONOMIC_ACTIVITY_INVALID {
            get {
                return ResourceManager.GetString("ECONOMIC_ACTIVITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à economicActivity is required..
        /// </summary>
        public static string ECONOMIC_ACTIVITY_REQUIRED {
            get {
                return ResourceManager.GetString("ECONOMIC_ACTIVITY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à email is invalid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ^\w+([-+.&apos;]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$.
        /// </summary>
        public static string EMAIL_REGEX {
            get {
                return ResourceManager.GetString("EMAIL_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à external user Identifier maximun length exceed..
        /// </summary>
        public static string EXTERNAL_USERID_MAXIMUM_LENGTH_EXCEED {
            get {
                return ResourceManager.GetString("EXTERNAL_USERID_MAXIMUM_LENGTH_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à externalUserId is required..
        /// </summary>
        public static string EXTERNAL_USERID_REQUIRED {
            get {
                return ResourceManager.GetString("EXTERNAL_USERID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à firstname maximun length exceed..
        /// </summary>
        public static string FIRSTNAME_MAXIMUN_LENGTH_EXCEED {
            get {
                return ResourceManager.GetString("FIRSTNAME_MAXIMUN_LENGTH_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à firstName is required..
        /// </summary>
        public static string FIRSTNAME_REQUIRED {
            get {
                return ResourceManager.GetString("FIRSTNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à lastname maximun length exceed..
        /// </summary>
        public static string LASTNAME_MAXIMUN_LENGTH_EXCEED {
            get {
                return ResourceManager.GetString("LASTNAME_MAXIMUN_LENGTH_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à lastName is required..
        /// </summary>
        public static string LASTNAME_REQUIRED {
            get {
                return ResourceManager.GetString("LASTNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à partnerCode is required..
        /// </summary>
        public static string PARTNER_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("PARTNER_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à password is required..
        /// </summary>
        public static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à resource login is required..
        /// </summary>
        public static string RESOURCE_LOGIN_REQUIRED {
            get {
                return ResourceManager.GetString("RESOURCE_LOGIN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à direction should be next or previous..
        /// </summary>
        public static string SEARCH_DIRECTION_BAD_VALUE {
            get {
                return ResourceManager.GetString("SEARCH_DIRECTION_BAD_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à direction is required..
        /// </summary>
        public static string SEARCH_DIRECTION_REQUIRED {
            get {
                return ResourceManager.GetString("SEARCH_DIRECTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à page size should be greater than zero..
        /// </summary>
        public static string SEARCH_PAGE_SIZE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("SEARCH_PAGE_SIZE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
    }
}
