//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizca.User.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bizca.User.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street is invalid..
        /// </summary>
        public static string ADDRESS_STREET_INVALID {
            get {
                return ResourceManager.GetString("ADDRESS_STREET_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zipCode is invalid..
        /// </summary>
        public static string ADDRESS_ZIPCODE_INVALID {
            get {
                return ResourceManager.GetString("ADDRESS_ZIPCODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addressName is invalid..
        /// </summary>
        public static string ADDRESSNAME_INVALID {
            get {
                return ResourceManager.GetString("ADDRESSNAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to birthCity is invalid..
        /// </summary>
        public static string BIRTHCITY_INVALID {
            get {
                return ResourceManager.GetString("BIRTHCITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to birthCountry is invalid..
        /// </summary>
        public static string BIRTHCOUNTRY_INVALID {
            get {
                return ResourceManager.GetString("BIRTHCOUNTRY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to birthDate is invalid..
        /// </summary>
        public static string BIRTHDATE_INVALID {
            get {
                return ResourceManager.GetString("BIRTHDATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to channel resource is required..
        /// </summary>
        public static string CHANNEL_RESOURCE_REQUIRED {
            get {
                return ResourceManager.GetString("CHANNEL_RESOURCE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to channelType is invalid..
        /// </summary>
        public static string CHANNEL_TYPE_INVALID {
            get {
                return ResourceManager.GetString("CHANNEL_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city is invalid..
        /// </summary>
        public static string CITY_INVALID {
            get {
                return ResourceManager.GetString("CITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city is required..
        /// </summary>
        public static string CITY_REQUIRED {
            get {
                return ResourceManager.GetString("CITY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to civility is invalid..
        /// </summary>
        public static string CIVILITY_INVALID {
            get {
                return ResourceManager.GetString("CIVILITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to civility is required..
        /// </summary>
        public static string CIVILITY_REQUIRED {
            get {
                return ResourceManager.GetString("CIVILITY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirmationCode is required..
        /// </summary>
        public static string CONFIRMATION_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("CONFIRMATION_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country is invalid..
        /// </summary>
        public static string COUNTRY_CODE_INVALID {
            get {
                return ResourceManager.GetString("COUNTRY_CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[A-Za-z]{2}$.
        /// </summary>
        public static string COUNTRY_CODE_REGEX {
            get {
                return ResourceManager.GetString("COUNTRY_CODE_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country is required..
        /// </summary>
        public static string COUNTRY_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("COUNTRY_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to economicActivity is invalid..
        /// </summary>
        public static string ECONOMIC_ACTIVITY_INVALID {
            get {
                return ResourceManager.GetString("ECONOMIC_ACTIVITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to economicActivity is required..
        /// </summary>
        public static string ECONOMIC_ACTIVITY_REQUIRED {
            get {
                return ResourceManager.GetString("ECONOMIC_ACTIVITY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email is invalid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\w+([-+.&apos;]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$.
        /// </summary>
        public static string EMAIL_REGEX {
            get {
                return ResourceManager.GetString("EMAIL_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to externalUserId is required..
        /// </summary>
        public static string EXTERNAL_USERID_REQUIRED {
            get {
                return ResourceManager.GetString("EXTERNAL_USERID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstName is required..
        /// </summary>
        public static string FIRSTNAME_REQUIRED {
            get {
                return ResourceManager.GetString("FIRSTNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastName is required..
        /// </summary>
        public static string LASTNAME_REQUIRED {
            get {
                return ResourceManager.GetString("LASTNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partnerCode is required..
        /// </summary>
        public static string PARTNER_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("PARTNER_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password is required..
        /// </summary>
        public static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource login is required..
        /// </summary>
        public static string RESOURCE_LOGIN_REQUIRED {
            get {
                return ResourceManager.GetString("RESOURCE_LOGIN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direction should be next or previous..
        /// </summary>
        public static string SEARCH_DIRECTION_BAD_VALUE {
            get {
                return ResourceManager.GetString("SEARCH_DIRECTION_BAD_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direction is required..
        /// </summary>
        public static string SEARCH_DIRECTION_REQUIRED {
            get {
                return ResourceManager.GetString("SEARCH_DIRECTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page size should be greater than zero..
        /// </summary>
        public static string SEARCH_PAGE_SIZE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("SEARCH_PAGE_SIZE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
    }
}
